version: "2"
services:
  web:
    build: .
    ports:
    - "9000:9000"
    volumes:
    - .:/app
    links:
    - rethinkdb
  rethinkdb:
    image: rethinkdb
    ports:
    - "28015:28015"
    - "8080:8080"
